### ISSUE TITLE
Missing important method of the official "BOARD" Lichess API in Berserk

### ISSUE THREAD

**Issue by tosca07** [rhgrant10/berserk#12]
* berserk version:8
* Python version:
* Operating System:

Description

Hello,
first of all thanks for this great Python API wrapper for the Lichess API - I really enjoy using it.

Some weeks ago lichess introduced the "board client" which I use to integrate it with my DGT Board.
I was happy to see that you already support this client but I am missing one method/command of the official lichess BOARD API: the seek command for creating an automatic challenge, see 

https://lichess.org/api/board/seek

Is it possible that you include this method?

Thanks
Dirk

**Comment by rhgrant10** [comment]
Thank you, much appreciated. Glad it's useful for you.

Adding this method is on the roadmap. Just need time. It's possible I'll get to it this weekend. Alternatively, I'm always accepting pull requests :wink:

**Comment by rhgrant10** [comment]
Available in [v0.9.0 on the PyPI](https://pypi.org/project/berserk/0.9.0/).

**Comment by tosca07** [comment]
Thank you so much (I would not have been able to do this :-(
Really appreciate your help and fast response!
Your API lib is really helping people like me who just started with python to be able to write an interface to lichess, so cool!
