### ISSUE TITLE
using API from Alexa skill to play unlimited engine game

### ISSUE THREAD

**Issue by rwst** [rhgrant10/berserk#44]
* berserk version:
* Python version:
* Operating System:

### Description

This is kind of checking if the idea is possible. Alexa skills are code (e.g. Python) hosted in the cloud, and are invoked by Alexa speech recognition. Provided someone has given their Lichess login credentials to the skill, do you think it possible they can play a game against the engine, unlimited time control? Do you see fundamental problems invoking the API from the cloud to do this? I'm a bit wobbly with this as I'm more of a desktop dev, less a web dev.

**Comment by Virinas-code** [comment]
I think it's possible. Everyone can invoke the API.

**Comment by rwst** [comment]
Thanks. I see now how this can work.
