### ISSUE TITLE
Challenges not customizable

### ISSUE THREAD

**Issue by tschmoderer** [rhgrant10/berserk#5]
* berserk version:0.3.1
* Python version:3.7
* Operating System: Ubuntu 19.04

### Description

trying to create a customized challenge. 

### What I Did

```
client.challenges.create(username="tschmoderer", rated=False, clock_limit=300, clock_increment=1)
```

no crash but the options were not taken into account. i got a correspondence unlimited challenge.

**Comment by WolfgangFahl** [comment]
What did you do about it?

**Comment by rhgrant10** [comment]
Thanks for reporting this. Just checked the relevant code and I see it's literally not passing along any of the options when it makes the post request. I'll release a fix soon (but probably after Christmas :sweat_smile:).

**Comment by PiR43** [comment]
I am also impacted by this bug. I use the color parameter when creating chalenge but for the moment the color is always random :-)

**Comment by rhgrant10** [comment]
Thanks @PiR43 and @WolfgangFahl for being patient with me over the holidays! This should be fixed in [v0.3.2 on the PyPI](https://pypi.org/project/berserk/0.3.2/)!

Please test this out and verify that it works as intended. I don't have a bot account I can test this with.

**Comment by rhgrant10** [comment]
Also thank you @tschmoderer for originally reporting this.

**Comment by PiR43** [comment]
@rhgrant10 Thanks, I have just updated the lib but need few days for test it (I use just the color param and need play few games for be sure the color is always good).

**Comment by PiR43** [comment]
I have done several tests and all are ok for the color parameter. Thanks.
