### ISSUE TITLE
error messages for 400 return codes

### ISSUE THREAD

**Issue by WolfgangFahl** [rhgrant10/berserk#6]
* berserk version: 0.3.1
* Python version: 3.7.4
* Operating System: Mac OS

### Description
According to  https://lichess.org/api some calls will return error information with a 404 status code e.g. "Authorization header missing". 

### What I Did

```
   def abort(self):
        try:
            self.client.bots.abort_game(self.game_id)
            return True
        except requests.exceptions.HTTPError as httpError:
            return self.handle(httpError)

   def handle(self,httpError):
        if self.debug:
            print (httpError)
        return False
```

The httpError does not seem to carry any detail information which might be necessary for a proper control flow.

**Comment by rhgrant10** [comment]
@WolfgangFahl per your comments on your PR, it was easier to just incorporate your changes. Versions 0.5.0 and later now provide custom exception types for response errors that exposes the HTTP code, reason, and also the cause of the error as reported by the API as attributes and in the exception message.
