### ISSUE TITLE
support for new broadcast API

### ISSUE THREAD

**Issue by WolfgangFahl** [rhgrant10/berserk#9]
*    berserk version: 0.3.1
*    Python version: 3.7.6
*    Operating System: Mac OS

### Description
There is a new API
https://lichess.org/api#tag/Broadcasts

### What I Did

Asked for broadcast api support and 
* https://github.com/ornicar/lila/issues/5834
* https://github.com/ornicar/lila/issues/5835
* https://github.com/ornicar/lila/issues/5838
were implemented. Now a python integration is the next needed step to make use of these great features.

**Comment by rhgrant10** [comment]
Thanks for bringing this new endpoint to my attention @WolfgangFahl. I'll add support for this soon. Also looking into ways of potentially generating a client from spec on a periodic basis. Stay tuned.

**Comment by WolfgangFahl** [comment]
see https://gitter.im/play-chess-with-a-webcam/community for where things are needed

**Comment by rhgrant10** [comment]
Hey @WolfgangFahl, broadcast support is now available on [v0.4.0 on PyPI](https://pypi.org/project/berserk/0.4.0/). Let me know if you find any problems. I'll be adding support for more missing endpoints soon.

**Comment by WolfgangFahl** [comment]
thx i'll get back to you a soon as i make progress.
